export const SOURCES_ROUTE = "/sources"
export const SETTINGS_ROUTE = "/settings"
export const DEVINFO_ROUTE = "/devInfo"
export const DEVSETTINGS_ROUTE = "/devSettings"
export const DEVCOMMANDS_ROUTE = "/devCommands"
export const ADVANCED_SETTINGS_ROUTE = "/advacncedSettings"
export const AUTHORIZATION_ROUTE = "/authorization"